# Generated by Django 4.0.3 on 2024-05-19 23:33

from django.db import migrations

def populate_db(apps, schema_editor):
    Producto = apps.get_model('tienda', 'Producto')
    CategoriaProd = apps.get_model('tienda', 'CategoriaProd')

    # Crear Categorías
    tec, created = CategoriaProd.objects.get_or_create(nombre='Tecnología')
    ropa, created = CategoriaProd.objects.get_or_create(nombre='Ropa')
    hogar, created = CategoriaProd.objects.get_or_create(nombre='Hogar')

    # Crear Productos
    Producto.objects.create(
        nombre="Smartphone X100", 
        categorias=tec, 
        precio=299.99, 
        disponibilidad=True
    )
    Producto.objects.create(
        nombre="Auriculares Inalámbricos", 
        categorias=tec, 
        precio=79.90, 
        disponibilidad=True
    )
    Producto.objects.create(
        nombre="Teclado Mecánico RGB", 
        categorias=tec, 
        precio=120.50, 
        disponibilidad=True
    )

    Producto.objects.create(
        nombre="Camiseta Básica de Algodón", 
        categorias=ropa, 
        precio=19.99, 
        disponibilidad=True
    )
    Producto.objects.create(
        nombre="Pantalones Vaqueros Slim Fit", 
        categorias=ropa, 
        precio=45.00, 
        disponibilidad=True
    )

    Producto.objects.create(
        nombre="Juego de Sábanas Queen", 
        categorias=hogar, 
        precio=55.00, 
        disponibilidad=True
    )
    Producto.objects.create(
        nombre="Lámpara de Escritorio LED", 
        categorias=hogar, 
        precio=35.20, 
        disponibilidad=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]